// Single source of truth for all blog post metadata.
// Consumed by: blog index (page.js), RSS feed (feed.xml/route.js), sitemap (sitemap.js).
// When adding a new blog post, add it here and update llms.txt / llms-full.txt.

export const blogPosts = [
  {
    slug: "understanding-uk-tax-code",
    title: "UK Tax Codes Explained: What Your Tax Code Means & How to Check It (2026/27)",
    description: "Complete guide to UK tax codes. Learn what each letter and number means, common codes like 1257L, BR, D0, K codes, Scottish S prefix, emergency tax codes, and what to do if yours is wrong.",
    date: "2026-04-09",
    readTime: "12 min read",
    category: "Tax Planning",
    featured: false,
    priority: 0.7,
  },
  {
    slug: "uk-tax-changes-2026-27",
    title: "UK Tax Changes 2026/27: What You Need to Know",
    description: "Complete guide to UK tax changes for 2026/27: frozen thresholds extended to 2031, Scottish band changes, +2pp dividend tax rise, SSP reform, new student loan thresholds and the £12.71 National Living Wage.",
    date: "2026-04-06",
    readTime: "11 min read",
    category: "Tax Updates",
    featured: true,
    priority: 0.8,
  },
  {
    slug: "uk-minimum-wage-2026-27",
    title: "UK Minimum Wage 2026/27: £12.71 NLW, Rates & Take-Home Pay",
    description: "Complete guide to UK minimum wage and National Living Wage rates from 1 April 2026. See the new £12.71 NLW, rates by age band, and exact take-home pay after tax.",
    date: "2026-04-06",
    readTime: "9 min read",
    category: "Salary Guide",
    featured: true,
    priority: 0.7,
  },
  {
    slug: "uk-dividend-tax-explained",
    title: "UK Dividend Tax Explained: Rates, Allowances & How to Calculate (2026/27)",
    description: "Complete guide to UK dividend tax for 2026/27. Learn about dividend tax rates (8.75%, 33.75%, 39.35%), the £500 allowance, how to calculate your bill, and strategies to reduce it.",
    date: "2026-03-31",
    readTime: "12 min read",
    category: "Tax Planning",
    featured: true,
    priority: 0.7,
  },
  {
    slug: "isa-vs-lisa",
    title: "Cash ISA vs Lifetime ISA (LISA): Which Is Right for You in 2026/27?",
    description: "Compare Cash ISAs and Lifetime ISAs side by side. See the 25% government bonus, withdrawal penalties, contribution limits, and which account suits your savings goals.",
    date: "2026-03-28",
    readTime: "10 min read",
    category: "Savings & ISAs",
    featured: true,
    priority: 0.7,
  },
  {
    slug: "paye-vs-self-employed",
    title: "PAYE vs Self-Employed Tax: Key Differences Explained for 2026/27",
    description: "Compare how tax works for employees and self-employed workers. See the NI savings, expenses rules, payment dates, and worked examples at different income levels.",
    date: "2026-03-28",
    readTime: "12 min read",
    category: "Tax Planning",
    featured: true,
    priority: 0.7,
  },
  {
    slug: "full-time-vs-part-time-tax",
    title: "Full-Time vs Part-Time Tax: How Working Hours Affect Your Take-Home Pay in 2026/27",
    description: "Do part-time workers pay less tax? Understand how UK tax bands, NI thresholds, and pro-rata benefits work when you reduce your hours.",
    date: "2026-03-28",
    readTime: "10 min read",
    category: "Tax Planning",
    featured: true,
    priority: 0.7,
  },
  {
    slug: "first-time-buyer-mortgage-guide",
    title: "First-Time Buyer Mortgage Guide 2026: Deposits, Schemes & Steps",
    description: "Complete first-time buyer mortgage guide for the UK. Learn about deposits, government schemes, stamp duty relief, affordability checks, and how to get your first mortgage.",
    date: "2026-03-27",
    readTime: "12 min read",
    category: "Money Tips",
    featured: true,
    priority: 0.7,
  },
  {
    slug: "how-to-pay-off-debt-faster",
    title: "How to Pay Off Debt Faster: Snowball vs Avalanche Strategy UK",
    description: "Learn the best strategies to pay off debt faster in the UK. Compare snowball vs avalanche methods, balance transfers, and consolidation with worked examples.",
    date: "2026-03-27",
    readTime: "10 min read",
    category: "Money Tips",
    featured: true,
    priority: 0.7,
  },
  {
    slug: "maternity-pay-guide",
    title: "Maternity Pay Guide 2026: SMP, Maternity Allowance & Shared Parental Leave",
    description: "Complete guide to maternity pay in the UK. Understand SMP eligibility, rates, how it compares to Maternity Allowance, and how to plan your finances.",
    date: "2026-03-27",
    readTime: "11 min read",
    category: "Salary Guide",
    featured: true,
    priority: 0.7,
  },
  {
    slug: "ssp-changes-2026",
    title: "SSP Changes 2026: What the New Sick Pay Rules Mean for You",
    description: "Major changes to Statutory Sick Pay are coming. Find out about the removal of waiting days, lower earnings limit changes, and what it means for your pay.",
    date: "2026-03-27",
    readTime: "10 min read",
    category: "Tax Updates",
    featured: true,
    priority: 0.7,
  },
  {
    slug: "uk-minimum-wage-2025-26",
    title: "UK Minimum Wage 2025/26: Hourly Rates, Take-Home Pay & Your Rights",
    description: "Historical reference: UK minimum wage and National Living Wage rates for 2025/26 (in force from April 2025 to April 2026). See what you'd have taken home after tax at every age band.",
    date: "2026-03-27",
    readTime: "9 min read",
    category: "Salary Guide",
    featured: true,
    priority: 0.7,
  },
  {
    slug: "two-jobs-tax-explained",
    title: "Two Jobs Tax Explained: How PAYE Works With Multiple Employers in the UK",
    description: "Understand how tax works when you have two jobs in the UK. Learn about tax codes, NI on multiple jobs, HMRC reconciliation, and how to avoid overpaying tax.",
    date: "2026-03-27",
    readTime: "12 min read",
    category: "Tax Planning",
    featured: true,
    priority: 0.7,
  },
  {
    slug: "pro-rata-salary-explained",
    title: "Pro-Rata Salary Explained: Part-Time Pay, Holiday & Pension in the UK",
    description: "Understand how pro-rata salary works for part-time workers in the UK. Learn to calculate your pay, holiday entitlement, pension, and tax implications.",
    date: "2026-03-27",
    readTime: "10 min read",
    category: "Salary Guide",
    featured: true,
    priority: 0.7,
  },
  {
    slug: "how-to-compare-job-offers",
    title: "How to Compare Job Offers: Salary, Benefits & Total Compensation UK",
    description: "Learn how to compare job offers beyond just salary. Understand pension match, healthcare, holidays, and total compensation to make the best career decision.",
    date: "2026-03-27",
    readTime: "10 min read",
    category: "Salary Guide",
    featured: true,
    priority: 0.7,
  },
  {
    slug: "scottish-tax-vs-english-tax",
    title: "Scottish Tax vs English Tax 2026/27: Who Pays More and By How Much?",
    description: "Scotland has 6 tax bands compared to England's 3. Here's exactly how much more (or less) you'd pay depending on your salary.",
    date: "2026-03-19",
    readTime: "12 min read",
    category: "Tax Planning",
    featured: true,
    priority: 0.7,
  },
  {
    slug: "plan-1-vs-plan-2-student-loan",
    title: "Plan 1 vs Plan 2 Student Loan: Key Differences Explained for 2026/27",
    description: "Not sure which plan you're on or how they compare? Here's everything about repayment thresholds, interest rates, and how much you'll actually repay.",
    date: "2026-03-19",
    readTime: "10 min read",
    category: "Student Loans",
    featured: true,
    priority: 0.7,
  },
  {
    slug: "salary-sacrifice-vs-personal-pension",
    title: "Salary Sacrifice vs Personal Pension: Which Saves You More Tax in 2026/27?",
    description: "Both get you tax relief on pension contributions — but salary sacrifice saves you National Insurance too. Here's exactly how much more you could save.",
    date: "2026-03-19",
    readTime: "12 min read",
    category: "Pensions",
    featured: true,
    priority: 0.7,
  },
  {
    slug: "supermarket-pay-rises-2026",
    title: "Supermarket Pay Rises 2026: How Tesco, Aldi, M&S, Lidl, Sainsbury's & Morrisons Compare",
    description: "Every major UK supermarket has announced new pay rates for 2026. Compare hourly rates from Aldi to Morrisons and see what you'll actually take home after tax.",
    date: "2026-03-18",
    readTime: "8 min read",
    category: "Salary Guide",
    featured: true,
    priority: 0.7,
  },
  {
    slug: "pay-rise-negotiation-guide",
    title: "How to Negotiate a Pay Rise in 2026: The Complete UK Guide",
    description: "Learn proven strategies to negotiate a higher salary in the UK, including when to ask, how much to request, and what you'll actually take home after tax.",
    date: "2026-01-29",
    readTime: "15 min read",
    category: "Salary Guide",
    featured: true,
    priority: 0.7,
  },
  {
    slug: "30k-salary-take-home",
    title: "\u00a330,000 Salary Take-Home Pay in 2026/27",
    description: "Complete breakdown of what you'll actually receive from a \u00a330k salary after income tax and National Insurance.",
    date: "2026-01-27",
    readTime: "5 min read",
    category: "Salary Guide",
    featured: true,
    priority: 0.7,
  },
  {
    slug: "40k-salary-take-home",
    title: "\u00a340,000 Salary Take-Home Pay in 2026/27",
    description: "See exactly how much you'll take home from a \u00a340k salary, including tax, NI, and student loan deductions.",
    date: "2026-01-27",
    readTime: "5 min read",
    category: "Salary Guide",
    featured: true,
    priority: 0.7,
  },
  {
    slug: "50k-salary-take-home",
    title: "\u00a350,000 Salary Take-Home Pay in 2026/27",
    description: "Detailed breakdown of a \u00a350k salary after tax - and why you're closer to the higher rate threshold than you think.",
    date: "2026-01-27",
    readTime: "5 min read",
    category: "Salary Guide",
    featured: true,
    priority: 0.7,
  },
  {
    slug: "60k-salary-take-home",
    title: "\u00a360,000 Salary Take-Home Pay in 2026/27",
    description: "What you'll actually take home from a \u00a360k salary, including the impact of the 40% higher rate tax band.",
    date: "2026-01-27",
    readTime: "5 min read",
    category: "Salary Guide",
    featured: true,
    priority: 0.7,
  },
  {
    slug: "20k-salary-take-home",
    title: "\u00a320,000 Salary Take-Home Pay in 2026/27",
    description: "Complete breakdown of what you'll actually receive from a \u00a320k salary after income tax and National Insurance.",
    date: "2026-04-09",
    readTime: "5 min read",
    category: "Salary Guide",
    featured: false,
    priority: 0.6,
  },
  {
    slug: "25k-salary-take-home",
    title: "\u00a325,000 Salary Take-Home Pay in 2026/27",
    description: "See exactly how much you'll take home from a \u00a325k salary, including tax, NI, and student loan deductions.",
    date: "2026-04-09",
    readTime: "5 min read",
    category: "Salary Guide",
    featured: false,
    priority: 0.6,
  },
  {
    slug: "35k-salary-take-home",
    title: "\u00a335,000 Salary Take-Home Pay in 2026/27",
    description: "Full breakdown of a \u00a335k salary after tax, National Insurance, and student loan deductions.",
    date: "2026-04-09",
    readTime: "5 min read",
    category: "Salary Guide",
    featured: false,
    priority: 0.6,
  },
  {
    slug: "45k-salary-take-home",
    title: "\u00a345,000 Salary Take-Home Pay in 2026/27",
    description: "What you'll take home from a \u00a345k salary \u2014 approaching the higher-rate threshold with a 20.2% effective tax rate.",
    date: "2026-04-09",
    readTime: "5 min read",
    category: "Salary Guide",
    featured: false,
    priority: 0.6,
  },
  {
    slug: "55k-salary-take-home",
    title: "\u00a355,000 Salary Take-Home Pay in 2026/27",
    description: "Detailed breakdown of a \u00a355k salary after tax \u2014 just crossed into the 40% higher rate band.",
    date: "2026-04-09",
    readTime: "5 min read",
    category: "Salary Guide",
    featured: false,
    priority: 0.6,
  },
  {
    slug: "65k-salary-take-home",
    title: "\u00a365,000 Salary Take-Home Pay in 2026/27",
    description: "Full tax breakdown for a \u00a365k salary \u2014 top 15% of UK earners, well into the higher rate band.",
    date: "2026-04-09",
    readTime: "5 min read",
    category: "Salary Guide",
    featured: false,
    priority: 0.6,
  },
  {
    slug: "70k-salary-take-home",
    title: "\u00a370,000 Salary Take-Home Pay in 2026/27",
    description: "What you'll take home from a \u00a370k salary after tax and NI. Top 10% of UK earners.",
    date: "2026-04-09",
    readTime: "5 min read",
    category: "Salary Guide",
    featured: false,
    priority: 0.6,
  },
  {
    slug: "75k-salary-take-home",
    title: "\u00a375,000 Salary Take-Home Pay in 2026/27",
    description: "Complete breakdown of a \u00a375k salary after tax, NI, and student loans. Tips to maximise with pension contributions.",
    date: "2026-04-09",
    readTime: "5 min read",
    category: "Salary Guide",
    featured: false,
    priority: 0.6,
  },
  {
    slug: "80k-salary-take-home",
    title: "\u00a380,000 Salary Take-Home Pay in 2026/27",
    description: "Full tax breakdown for \u00a380k \u2014 top 5% of UK earners with 28.8% effective tax rate.",
    date: "2026-04-09",
    readTime: "5 min read",
    category: "Salary Guide",
    featured: false,
    priority: 0.6,
  },
  {
    slug: "85k-salary-take-home",
    title: "\u00a385,000 Salary Take-Home Pay in 2026/27",
    description: "What you'll take home from \u00a385k after tax and NI. Approaching the \u00a3100k Personal Allowance taper.",
    date: "2026-04-09",
    readTime: "5 min read",
    category: "Salary Guide",
    featured: false,
    priority: 0.6,
  },
  {
    slug: "90k-salary-take-home",
    title: "\u00a390,000 Salary Take-Home Pay in 2026/27",
    description: "Full breakdown of a \u00a390k salary after tax. Just \u00a310k from the Personal Allowance taper zone.",
    date: "2026-04-09",
    readTime: "5 min read",
    category: "Salary Guide",
    featured: false,
    priority: 0.6,
  },
  {
    slug: "95k-salary-take-home",
    title: "\u00a395,000 Salary Take-Home Pay in 2026/27",
    description: "What you'll take home from \u00a395k \u2014 \u00a35k below the \u00a3100k tax trap. Pension sacrifice strategies included.",
    date: "2026-04-09",
    readTime: "5 min read",
    category: "Salary Guide",
    featured: false,
    priority: 0.6,
  },
  {
    slug: "100k-salary-take-home",
    title: "\u00a3100,000 Salary Take-Home Pay in 2026/27",
    description: "Complete breakdown of a \u00a3100k salary after tax, plus the \u00a3100k tax trap explained and how to avoid 60% effective rate.",
    date: "2026-04-09",
    readTime: "5 min read",
    category: "Salary Guide",
    featured: false,
    priority: 0.7,
  },
  {
    slug: "student-loan-refund",
    title: "Are You Owed Money? The Student Loan Refund Thousands of UK Graduates Are Missing",
    description: "Over 1 million student loan overpayments happened last year. Here's how to check if you're one of them\u2014and get your money back.",
    date: "2026-01-25",
    readTime: "16 min read",
    category: "Student Loans",
    featured: true,
    priority: 0.6,
  },
  {
    slug: "cash-isa-limit-2027",
    title: "The \u00a312,000 Cash ISA Limit: What You Need to Know Before April 2027",
    description: "Your tax-free savings allowance is about to change. From April 2027, under-65s can only deposit \u00a312,000 per year into cash ISAs. Here's what it means for your money.",
    date: "2026-01-25",
    readTime: "18 min read",
    category: "Savings & ISAs",
    featured: true,
    priority: 0.6,
  },
  {
    slug: "100k-tax-trap",
    title: "The \u00a3100k Tax Trap: Britain's Hidden 60% Tax Rate That's Punishing Middle-Class Professionals",
    description: "How earning over \u00a3100,000 creates a 60% effective tax rate affecting nearly 2 million professionals.",
    date: "2026-01-25",
    readTime: "20 min read",
    category: "Tax Planning",
    featured: true,
    priority: 0.6,
  },
  {
    slug: "salary-sacrifice-changes-2029",
    title: "Salary Sacrifice Pension Changes from April 2029: What You Need to Know",
    description: "From April 2029, only the first \u00a32,000 of pension contributions through salary sacrifice will be exempt from National Insurance.",
    date: "2025-11-26",
    readTime: "7 min read",
    category: "Pensions",
    featured: true,
    priority: 0.6,
  },
  {
    slug: "uk-tax-changes-2025-26",
    title: "UK Tax Changes 2025/26: What You Need to Know",
    description: "Complete guide to the latest tax rates, thresholds, and changes affecting your take-home pay this tax year.",
    date: "2025-04-06",
    readTime: "8 min read",
    category: "Tax Updates",
    featured: true,
    priority: 0.6,
  },
  {
    slug: "uk-tax-changes-2024-25",
    title: "UK Tax Changes 2024/25: What You Need to Know",
    description: "Complete guide to the latest tax rates, thresholds, and changes affecting your take-home pay this tax year.",
    date: "2024-04-06",
    readTime: "8 min read",
    category: "Tax Updates",
    featured: true,
    priority: 0.6,
  },
  {
    slug: "maximize-take-home-pay-2024",
    title: "10 Legal Ways to Maximize Your Take-Home Pay in 2024",
    description: "From salary sacrifice to pension contributions - discover proven strategies to keep more of your hard-earned money.",
    date: "2024-03-15",
    readTime: "12 min read",
    category: "Money Tips",
    featured: true,
    priority: 0.6,
  },
  {
    slug: "student-loan-repayment-guide",
    title: "Student Loan Repayment Calculator Guide: Plans 1, 2 & 5 Explained",
    description: "Everything you need to know about student loan repayments, interest rates, and when loans get written off.",
    date: "2024-03-01",
    readTime: "10 min read",
    category: "Student Loans",
    featured: false,
    priority: 0.6,
  },
  {
    slug: "salary-sacrifice-complete-guide",
    title: "Salary Sacrifice: Complete Guide to Tax-Free Benefits",
    description: "How salary sacrifice works, available schemes, and how much you could save on tax and National Insurance.",
    date: "2024-02-20",
    readTime: "15 min read",
    category: "Tax Planning",
    featured: false,
    priority: 0.6,
  },
  {
    slug: "self-employed-tax-calculator-guide",
    title: "Self-Employed Tax Calculator: How to Estimate Your Tax Bill",
    description: "Calculate your income tax, National Insurance, and take-home profit as a sole trader or freelancer.",
    date: "2024-02-05",
    readTime: "9 min read",
    category: "Self-Employment",
    featured: false,
    priority: 0.6,
  },
  {
    slug: "pension-contributions-tax-relief",
    title: "Pension Contributions and Tax Relief: Maximize Your Retirement Savings",
    description: "Understanding annual allowances, tax relief rates, and how pension contributions reduce your tax bill.",
    date: "2024-01-25",
    readTime: "11 min read",
    category: "Pensions",
    featured: false,
    priority: 0.6,
  },
];

export const blogCategories = [
  "All",
  "Salary Guide",
  "Tax Updates",
  "Money Tips",
  "Student Loans",
  "Tax Planning",
  "Self-Employment",
  "Pensions",
  "Savings & ISAs",
];
